### ISSUE TITLE
Screenshots should be saved regardless of whether the test is successful

### ISSUE THREAD

**Issue by cchan** [mdmintz/SeleniumBase#35]
If the whole Selenium CSS selection thing still works, but we broke something critical in the UI appearance, then it's practically impossible to reliably automatically test this, but the screenshot can indicate what was on the screen at that time in that browser.

(This might be better solved by just opening it up and interacting with the interface yourself in a browser, but for the sake of completeness it really feels like screenshots should be saved always.)

**Comment by mdmintz** [comment]
There's the save_screenshot() method to save screenshots at times other than test failures. A failure is a natural place to have a screenshot taken automatically because that's when something went wrong. Otherwise, there'd be no way to know where to have them. If you take a screenshot after every single action like a click, it's going to take up a lot of unnecessary disk space. And even then, you might not know that anything was wrong unless you looked through all the screenshots. The real problem here is the reason behind why I created MasterQA https://github.com/mdmintz/MasterQA . It's for when you want human eyes to look at something, but still have automation do all the heavy lifting so that manual QA time is minimized. Check out that repo to see for yourself.

**Comment by mdmintz** [comment]
Hi @cchan, you can add ``--ss`` as a ``pytest`` command-line option to save a screenshot after every test that runs!

```python
pytest --ss
```
