### ISSUE TITLE
observation: driver.Implicitly_wait() does not make the browser wait

### ISSUE THREAD

**Issue by surevs** [mdmintz/SeleniumBase#57]
unsure why a driver.implicitly_wait ( ) does not work with seleniumbase just the way it works with selenium, though there are options provided for wait for element after a specific time out. There is a big possibility that we might need to perform something similar to time.sleep() , Any thoughts/suggestions around this

**Comment by mdmintz** [comment]
Actions such as self.click(css_selector) and self.update_text(css_selector, text) automatically wait for the elements to be visible before trying to interact with them. Therefore, you should never need to to use self.driver.implicitly_wait(seconds). I've never needed it with SeleniumBase. If you just want your test to wait around for no reason, then maybe you can use time.sleep(seconds). Otherwise, you shouldn't need it.

**Comment by surevs** [comment]
The resolution is definitely very accurate and clear. but just thought to highlight around the observation made.
Thank you!

**Comment by mdmintz** [comment]
Update your links. SeleniumBase is now located at https://github.com/seleniumbase/SeleniumBase
